stages:
  - prepare
  - build
  - deploy

variables:
  LC_ALL: "en_US.UTF-8"
  PILOT_USERNAME: "apple.railwaymen.ci@gmail.com"
  SIGH_USERNAME: "apple.railwaymen.ci@gmail.com"

cache:
  key: "bundle_dependencies"
  paths:
  - vendor

prepare_proj:
  stage: prepare
  script:
    - cd Example
    - rvm use 2.6.0@CoordinatorsFoundation
    - bundle install --path=/Users/xcodeserver/gitlab-runner/builds/shared/CoordinatorsFoundation/gems
    - bundle exec pod install || bundle exec pod install --repo-update
    - export
  artifacts:
    name: "Bundle_${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}"
    expire_in: 1 day
    paths:
      - Example/Pods/*
      - Example/CoordinatorsFoundation.xcworkspace
  when: on_success
  tags:
    - ios

test_project:
  stage: build
  before_script:
    - killall "Simulator" || true
  script:
    - export
    - cd Example
    - rvm use 2.6.0@CoordinatorsFoundation
    - bundle install --path=/Users/xcodeserver/gitlab-runner/builds/shared/CoordinatorsFoundation/gems
    - bundle exec fastlane test
  after_script:
    - killall "Simulator" || true
  artifacts:
    name: "Tests_${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}"
    expire_in: 1 week
  when: on_success
  dependencies:
    - prepare_proj
  tags:
    - ios_simulator
  coverage: '/CoordinatorsFoundation\.framework\D*\|\D*([\d\.]*)\%/'

deploy_patch:
  stage: deploy
  dependencies:
    - test_project
  script:
    - export
    - cd Example
    - bundle exec fastlane release bump_type:"patch"
  artifacts:
    name: "Deploy_${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}"
    expire_in: 1 week
  when: manual
  tags:
    - ios
  only:
    - release/patch

deploy_minor:
  stage: deploy
  dependencies:
    - test_project
  script:
    - export
    - cd Example
    - bundle exec fastlane release bump_type:"minor"
  artifacts:
    name: "Deploy_${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}"
    expire_in: 1 week
  when: manual
  tags:
    - ios
  only:
    - release/minor

deploy_major:
  stage: deploy
  dependencies:
    - test_project
  script:
    - export
    - cd Example
    - bundle exec fastlane release bump_type:"major"
  artifacts:
    name: "Deploy_${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}"
    expire_in: 1 week
  when: manual
  tags:
    - ios
  only:
    - release/major
